config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :meetings do
  end

  devise_for :users
  get 'active-sessions', to: "meetings#active_sessions"
  root to: 'home#index'
  resources :users, only: [:index]
  resources :menu, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meetings,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin, only: [:active_sessions]

  # GET /meetings
  # GET /meetings.json
  def index
    if current_user.admin?
      @meetings = Meeting.all
    else
      @meetings = current_user.meetings.where(user_id: current_user)
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create

    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id


    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def active_sessions
    @active_sessions = Meeting.where("end_time > ?", Time.now)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id)
    end

    def must_be_admin
      unless current_user.try(:admin?)
        redirect_to meetings_path, alert: "You don't have access to this page"
      end
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
    before_action :authenticate_user!
    before_action :must_be_admin, only: [:active_sessions]

    def index
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :must_be_admin
  
    def index
      @users = User.all
    end
  
    private
  
    def must_be_admin
      unless current_user.try(:admin?)
        redirect_to meetings_path, alert: "You don't have access to this page"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def readable_time(time)
    time.strftime("%b %d, %I:%M%P")
  end

  def author_of(record)
    user_signed_in? && current_user.id == record.user_id
  end

  def admin?
    user_signed_in? && current_user.admin?
  end

end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/home/index.html.erb
<div class="py-10 lg:py-10 px-4 mb-4 text-indigo-700">
  <div class="container m-auto text-center">
    <h1 class="text-xl lg:text-3xl">Welcome to <%= "RBEAUT" %>!</h1>
    <p class="lead my-2 max-w-md m-auto leading-normal text-grey-700 text-lg mb-4">Get styled by RBEAUT Fashion Salon experts who bring you the latest runway trends in skin, hair and makeup. Get your beauty journey started!
    </p>

    <br/>
    <% unless user_signed_in? %>
    <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary my-3" %>
    <% else %>
    <%= link_to "Schedule a new Reservation", new_meeting_path, class:"btn btn-primary my-3" %>
    <% end %>
  </div>
</div>


<div class="max-w-lg m-auto">
  <div class="py-8 lg:py-16 px-4 flex flex-wrap items-center justify-between">

    <div class="lg:w-1/2 w-full mb-4 lg:mb-0">
      
      <p class="leading-normal">Our runway experts have curated some of the most popular services at RBEAUT Salon, just for you. Take your pick, reserve your time and head to your nearest salon and get started on your makeover!</p>
    </div>

    <div class="lg:w-1/2 w-full text-center">
      <%= image_tag 'teacher.svg', alt: "Become a pro", width: 400 %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "RBEAUT" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>

  </head>

 <body class="bg-grey-lighter">
  
    <header class="bg-white">
      <nav class="flex items-center justify-between flex-wrap bg-grey-lightest p-4 text-grey-darker border-b border-grey-light">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= link_to root_path, class:"link text-xl tracking-tight font-semibold" do %>
            <%= "RBEAUT" %>
          <% end %>
        </div>
        
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-grey hover:text-grey-dark hover:border-grey-dark">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end">
            <% unless user_signed_in? %>
            <%= link_to "Login", new_user_session_path, class:"btn btn-default mr-2" %>
            <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default" %>
            <% else %>
            <%= link_to "Our Services", menu_index_path, class:"btn btn-menu mr-2" %>
            <%= link_to "Dashboard", meetings_path, class: "btn btn-default mr-2" %>
            <%= link_to "New reservation", new_meeting_path, class: "btn btn-default mr-2" unless admin? %>
            <%= link_to "Users", users_path, class: "btn btn-default mr-2" if admin? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-default mr-2" %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/meetings/_calendar.html.erb
<%= month_calendar events: meetings do |date, meetings| %>
    <%= date %>
    <% meetings.each do |meeting| %>
      <div>
        <%= link_to meeting.name, meeting, class: "link" %>
      </div>
    <% end %>
  <% end %>
  

app/views/meetings/_form.html.erb
<div class="p-10 bg-white border border-grey-200 rounded">
<%= form_with(model: meeting, local: true, class: "meeting-form") do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="mb-4 text-2xl">Reservation Information</h3>

  <div class="mb-6">
    <%= form.label :service, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :mobile, class: "label" %>
    <%= form.text_field :mobile, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :start_time, class: "label" %>
    <div class="flex items-center justify-between max-w-md">
      <%= form.datetime_select :start_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-3" } %>
    </div>
  </div>

  <div class="field">
    <%= form.label :end_time, class: "label" %>
    <div class="flex items-center justify-between max-w-md">
      <%= form.datetime_select :end_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 15 }, { class: "select py-2 px-2 mr-2" } %>
    </div>
  </div>

  <br/><br/>
  <%= form.submit  class: "btn btn-primary text-base py-3 px-5" %>

<% end %>
</div>

app/views/meetings/_meetings_cta.html.erb
<div class="max-w-md my-10 m-auto p-12 lg:p-16 bg-white rounded border border-grey-light text-center shadow">
  <%= image_tag "schedule.svg", alt: "schedule", width: 300, class: "mb-4" %>
  <h1 class="text-indigo-darker text-2xl mb-6">It looks like no reservation have been set with us yet</h1>
  <%= link_to "Schedule a new session", new_meeting_path, class: "btn btn-primary py-3 px-5 " %>
</div>

app/views/meetings/_meetings_landing.html.erb
<nav class="bg-white mb-4 shadow rounded">
  <ul id="nav-tab" class="tabs list-reset flex">

    <li class="active" data-tab="calendar">
      <%= link_to "#calendar", class: "tab flex items-center" do %>
       <svg viewBox="0 0 20 20" width="16" height="16" class="fill-current text-grey-light mr-2"><title>calendar</title><path d="M1 4c0-1.1.9-2 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4zm2 2v12h14V6H3zm2-6h2v2H5V0zm8 0h2v2h-2V0zM5 9h2v2H5V9zm0 4h2v2H5v-2zm4-4h2v2H9V9zm0 4h2v2H9v-2zm4-4h2v2h-2V9zm0 4h2v2h-2v-2z"></path></svg>
       Calendar
      <% end %>
    </li>

     <li data-tab="all-meetings">
      <%= link_to "#all-meetings", class: "tab flex items-center" do %>
      <svg viewBox="0 0 20 20" class="fill-current text-grey-light mr-2" width="16" height="16"><title>coffee</title><path d="M4 11H2a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h2V1h14v10a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4zm0-2V5H2v4h2zm-2 8v-1h18v1l-4 2H6l-4-2z"></path></svg>
      All Reservations
      <% end %>
    </li>

  </ul>
</nav>

<div class="bg-white p-10 border rounded">
  
  <div id="calendar" class="tab-panel active">
    <p class="text-2xl"><strong>Reservations Calendar</strong></p>
    <br/>
    <div id="meeting-calendar">
      <%= render "calendar", meetings: meetings  %>
    </div>
  </div>

  <div id="all-meetings" class="tab-panel ">

     <p class="text-2xl">Reservations</p>

     <br/>

     <% meetings.each do |meeting| %>
        <div class="flex flex-wrap items-center justify-start p-4 border-b border-grey-800 mb-6">
          <div class="flex-1 flex justify-between">
            <div>
              <%= link_to meeting.name, meeting, class: "link mr-4" %>
            </div>
            <div>
              <%= readable_time(meeting.start_time) %> &ndash;
              <%= readable_time(meeting.end_time) %>
            </div>
          </div>
        </div>

        <%= link_to "Cancel Reservation", meeting, method: :delete, data: { confirm: "Are you sure? There are no refunds." }, class: "btn btn-destroy ml-4" if admin? %>
     <% end %>
  </div>

</div>

app/views/meetings/edit.html.erb
<div class="max-w-lg m-auto px-0.5">
  <h1 class="text-3xl mt-10">Edit your Reservation</h1>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/index.html.erb
<div class="container m-auto my-4">
  <% unless current_user.meetings.any? %>
    <%= render "meetings_cta" %>
  <% else %>
    <%= render "meetings_landing", meetings: @meetings %>
  <% end %>
</div>

app/views/meetings/new.html.erb
<div class="max-w-lg m-auto px-0.5">
  <h1 class="text-3xl text-center mt-10">Schedule a new Reservation</h1>
  <br/><br/>
  <%= render 'form', meeting: @meeting %>
</div>

app/views/meetings/show.html.erb
<div class="py-10 max-w-lg my-10  m-auto">
  <div class="p-3 bg-white border border-grey-300 rounded">

    <div class="flex flex-wrap justify-between items-center mb-5">
      <p class="text-3xl px-3 mr-10 text-indigo-500"><%= @meeting.name %></p>
      <%= link_to "Edit Service", edit_meeting_path, data: { confirm: "Are you sure you want to edit your reservation? "}, class: "ml-10 btn btn-primary" %>
      <%= link_to "Finish Service", meeting_path(@meeting), method: :delete, data: { confirm: "Are you sure you want to cancel? "}, class: "mr-2 btn btn-destroy" if admin? %>
    </div>

    <div class="border p-6 bg-grey-400 mb-5 rounded flex items-center justify-between">
      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo-700">
        Start time: <span class="font-bold"><%= readable_time(@meeting.start_time) %></span>
      </p>
      <div class="border-t-2 border-indigo-200 border-dashed h-1 flex-1"></div>
      <p class="border-2 py-3 px-4 border-indigo rounded-full text-sm text-indigo-700">
        End time: <span class="font-bold"><%= readable_time(@meeting.end_time) %></span>
      </p>
    </div>

  
    <% unless user_signed_in? %>
      <div class="bg-grey-200 rounded p-4 mt-4 text-center">
        <p class="text-sm text-grey-700"><%= link_to "Login", new_user_session_path, class: "link" %> or <%= link_to "Sign up", new_user_regsitration_path, class: "link" %> to comment.</p>
      </div>
    
  <% end %>

</div>
</div>

app/views/menu/index.html.erb
<div class="bg-indigo-700 m-10 p-10 border rounded">

    <p class="text-3xl text-white">Our Services</p>
    <br/><br/>

    <div class="container mx-auto w-full flex flex-wrap justify-between mx-2">

    <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 border-b sm:border-r lg:border-b-0 pb-6 pt-6 lg:pt-3">
        <h3 class="font-bold text-xl text-white underline text-bold mb-2">Hair Cut</h3>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Haircut</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-150</div>           
            </div>
        </li>
            
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Haircut Style Change</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-170</div>           
            </div>
        </li>

        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Beard Shave</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-100</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Kids Cut</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-130</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Beard Shaping</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-100</div>           
            </div>
        </li>
      </ul>


      <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 border-b sm:border-r-0 lg:border-r lg:border-b-0 pb-6 pt-6 lg:pt-3">
        <h3 class="font-bold text-xl text-white underline text-bold mb-2">Coloring</h3>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Basic Coloring</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-500</div>           
            </div>
        </li>
            
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Ammonia Free</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-1000</div>           
            </div>
        </li>

        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Beard Coloring</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-700</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Creative Coloring</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-1500</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Streak (per streak)</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-400</div>           
            </div>
        </li>
      </ul>


      <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 border-b sm:border-r-0 lg:border-r lg:border-b-0 pb-6 pt-6 lg:pt-3">
        <h3 class="font-bold text-xl text-white underline text-bold mb-2">Hair Spa</h3>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Classis Hair Spa</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-450</div>           
            </div>
        </li>
            
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Frizz Ease</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-650</div>           
            </div>
        </li>

        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Repair & Rejuvenate</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-700</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Argan Oil Hair Spa</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-1000</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Smoothening Spa</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-800</div>           
            </div>
        </li>
      </ul>


      <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 pb-6 pt-6 lg:pt-3">
        <h3 class="font-bold text-xl text-white underline text-bold mb-2">Make Up</h3>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Cleanse & Lashes</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-400</div>           
            </div>
        </li>
            
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Mini Facial</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-650</div>           
            </div>
        </li>

        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Natural Facial</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-750</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Manicure & Nail Repair</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-500</div>           
            </div>
        </li>
        <li>
            <div class="flex justify-between">
                <div class="text-white text-xl pb-4 pt-3 text-center ">Bridal Makeup</div>
                <div class="text-white text-xl pb-4 pt-3 justify-end text-center ">-2000</div>           
            </div>
        </li>
      </ul>

    </div>
    
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading flex flex-wrap justify-between items-center">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: "btn btn-default my-2", id: "previous-month" %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: "btn btn-default my-2", id: "next-month" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th class="text-sm text-grey-700"><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_user.html.erb
<% if user.meetings.any? %>

<div class="flex flex-wrap items-center mb-5 text-indigo-700">
  <div class="flex-1 flex justify-between items-center">
    <div><h3 class="text-lg"><%= user.name %></h3>(<%= user.username %>)</div>
    <p>Joined on <%= readable_time(user.created_at) %></p>

  </div>
</div>

<% if user.meetings.any? %>
  <div class="block pl-2 border-l border-indigo-300 mb-5">
    <p class="text-lg uppercase tracking-loose text-grey-700 pt-1">Upcoming Reservations</p>
    <% user.meetings.each do |meeting| %>
        <%= link_to meeting.name, meeting, class: "link my-2 inline-block" %><br/>
    <% end %>
  </div>
<% end %>

<% end %>

app/views/users/index.html.erb
<div class="container m-auto bg-white my-10 border border-grey-300 p-6">
  <h1 class="text-indigo-700 text-2xl pb-2 border-b border-grey-300 mb-4">Users</h1>
  <%= render @users %>
</div>